length = int(input("enter your length :"))
bredth = int(input("enter your bredth :"))
height = int(input("enter your height :"))
area = 2*(length*bredth + bredth*height + length*height)
print("the area of cuboid is :",area)
